Repository Akvariet/P2, pull requests merged in 2021-04, with the labels that each got.

#48 App is now running on a third party PeerJS server.
  public/js/voice.js
  scripts/serverConfig.js
Labels: bug

#49 Implemented proximity voice chat
  public/js/interaction.js
  public/js/main.js
  public/js/proxi.js
  public/js/voice.js
Labels: enhancement

#46 Spinner rework
  public/css/room.css
  public/index.html
  public/js/ClientConnection.js
  public/js/frontend-spinner.js
  public/js/interaction.js
  public/js/login.js
  public/js/main.js
  public/js/proxi.js
  scripts/AkvarioServer.js
  scripts/ColorPicker.js
  scripts/backend-spinner.js
Labels: enhancement

#56 fixed issue "Users colors get black during spinner game #55"
  public/js/frontend-spinner.js
Labels: bug

#58 added config to login
  public/js/clientConfig.js
  public/js/login.js
Labels: bug

#59 Testing added.
  public/js/proxi.js
  test/AkvarioTest.js
  test/client/proxiTest.js
  test/server/akvarioServerTest.js
  test/server/colorPickerTest.js
  test/testClasses.js
Labels: enhancement

#60 Added visuals so users can see when someone is speaking
  public/css/room.css
  public/js/ClientConnection.js
  public/js/voice.js
  public/js/voiceAnalysis.js
  scripts/AkvarioServer.js
Labels: enhancement

#66 added our own peer server back
  public/js/voice.js
Labels: bug

#69 Added mute and deafen functionalities + design
  public/css/room.css
  public/index.html
  public/js/interaction.js
  public/js/popUpMenu.js
  public/js/proxi.js
  public/js/voice.js
  public/resources/menuBody.svg
  public/resources/mic-fill.svg
  public/resources/mic-mute-fill.svg
  public/resources/speakerIcon.svg
  public/resources/speakerIconMuted.svg
  public/resources/volume-mute-fill.svg
  public/resources/volume-up-fill.svg
  scripts/AkvarioServer.js
Labels: enhancement

#67 removed PeerJS Server
  package.json
  scripts/AkvarioServer.js
  scripts/serverConfig.js
  server.js
Labels: enhancement

#63 fixed bug with cameramove
  public/js/ClientConnection.js
  public/js/cameraMove.js
  public/js/interaction.js
  public/js/popUpMenu.js
  scripts/AkvarioServer.js
Labels: bug, enhancement

#79 Voice.js refactor and more
  package.json
  public/index.html
  public/js/ClientConnection.js
  public/js/PeerConnection.js
  public/js/clientConfig.js
  public/js/interaction.js
  public/js/login.js
  public/js/popUpMenu.js
  scripts/serverConfig.js
  scripts/user.js
Labels: enhancement

#83 Error validation
  public/js/ClientConnection.js
  public/js/voice.js
  scripts/AkvarioServer.js
  scripts/user.js
Labels: bug, enhancement

#82 changed from requestanimationframe to setTimeout
  public/js/voiceAnalysis.js
Labels: enhancement

#85 Spinner game area
  public/css/room.css
  public/index.html
  public/js/ClientConnection.js
  public/js/frontend-spinner.js
  public/js/interaction.js
  scripts/AkvarioServer.js
  scripts/backend-spinner.js
Labels: enhancement

#86 fixed cameramove and refactored code
  public/js/ClientConnection.js
  public/js/cameraMove.js
  public/js/interaction.js
  public/js/popUpMenu.js
Labels: enhancement

#88 Deafmute
  public/css/login.css
  public/css/room.css
  public/index.html
  public/js/ClientConnection.js
  public/js/interaction.js
  public/js/popUpMenu.js
  scripts/AkvarioServer.js
Labels: enhancement

#99 reimplemented body-display
  public/css/room.css
  public/js/main.js
  public/js/popUpMenu.js
Labels: bug
