Repository Akvariet/P2, pull requests merged in 2021-05, with the labels that each got.

#105 backend Spinner test implementation
  public/js/popUpMenu.js
  scripts/backendSpinner.js
  test/AkvarioTest.js
  test/server/backendSpinnerTest.js
  test/testClasses.js
Labels: documentation

#107 App is now AAU Ready
  public/js/clientConfig.js
  public/js/login.js
  public/js/main.js
  public/js/popUpMenu.js
Labels: bug

#108 Counter implementation
  public/js/login.js
  scripts/AkvarioServer.js
Labels: enhancement

#116 Test Client
  package.json
  test/client/testClient.js
Labels: enhancement

#119 Clean up, comments and removed all logs
  scripts/AkvarioServer.js
  start.bat
  test/AkvarioTest.js
  test/client/testClient.js
  test/server/akvarioServerTest.js
  test/testServer.js
Labels: Important, enhancement

#120 Added stuff to README.md and deleted peerjs.min.js
  README.md
  package.json
  public/index.html
  public/js/peerjs/peerjs.min.js
  start.bat
  startTest.bat
Labels: Important, documentation, enhancement
