Repository Akvariet/P2, pull requests merged in 2021-03, with the labels that each got.

#27 PopUpMenu and PopUpMenu not showing when player is moving
  package-lock.json
  package.json
  public/css/login.css
  public/css/normal.css
  public/index.html
  public/js/main.js
  public/js/userClient.js
  public/resources/menuBody.svg
  public/resources/speakerIcon.svg
  public/resources/speakerIconMuted.svg
  scripts/user.js
Labels: enhancement

#29 Color fix
  public/css/login.css
  public/index.html
  public/js/main.js
  public/js/user.js
  public/js/userClient.js
  server.js
Labels: enhancement

#30 Spinner implemented in room, and should be fully functional
  public/css/frontend-spinner.css
  public/css/normal.css
  public/frontend-spinner.html
  public/index.html
  public/js/frontend-spinner.js
  public/js/main.js
  scripts/backend-spinner.js
  server.js
Labels: documentation, enhancement

#28 Voice P2P implemented
  public/css/login.css
  public/css/normal.css
  public/index.html
  public/js/color.js
  public/js/main.js
  public/js/user.js
  public/js/userClient.js
  server.js
Labels: enhancement

#34 Proxi chat functionality almost implemented.
  public/js/proxi.js
  public/js/userClient.js
Labels: enhancement

#39 Clean up
  .gitignore
  package.json
  public/css/frontend-spinner.css
  public/css/login.css
  public/css/normal.css
  public/css/room.css
  public/frontend-spinner.html
  public/index.html
  public/js/ClientConnection.js
  public/js/client.js
  public/js/frontend-spinner.js
  public/js/interaction.js
  public/js/login.js
  public/js/main.js
  public/js/proxi.js
  public/js/user.js
  public/js/userClient.js
  public/js/voice.js
  public/mainPage.html
  public/resources/menuBody.svg
  public/resources/speakerIcon.svg
  public/resources/speakerIconMuted.svg
  routes/index.js
  scripts/AkvarioServer.js
  scripts/backend-spinner.js
  scripts/connection.js
  scripts/routes.js
  scripts/user.js
  server.js
Labels: enhancement

#40 Clients no longer multiply on connection.
  public/js/ClientConnection.js
Labels: bug

#41 Colorfix2
  public/js/ColorPicker.js
  public/js/client.js
  public/js/login.js
  public/js/main.js
  public/resources/colorPalette.js
  scripts/AkvarioServer.js
  server.js
Labels: enhancement

#44 Working PeerJS and PeerJS Server.
  README.md
  package.json
  public/index.html
  public/js/ClientConnection.js
  public/js/clientConfig.js
  public/js/interaction.js
  public/js/main.js
  public/js/voice.js
  scripts/AkvarioServer.js
  scripts/routes.js
  scripts/serverConfig.js
  server.js
Labels: enhancement
